language: cpp

os:
  - linux
  - osx

env:
  matrix:
   - N_PLATFORM="io" N_VERSION="2.3.0"
   - N_PLATFORM="io" N_VERSION="1.8.2"
   - N_PLATFORM="io" N_VERSION="1.0.4"
   - N_PLATFORM="node" N_VERSION="0.12.4"
   - N_PLATFORM="node" N_VERSION="0.10.38"

before_install:
  - rm -rf ~/.nvm
  - export JOBS=max
  - git clone https://github.com/ralphtheninja/n.git ./scripts/n
  - sudo chmod -R a+xw /usr/local

before_script:
  - export PATH=./scripts/n/bin:./node_modules/.bin/:$PATH
  - export COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
  - env

script:
  - ./scripts/linux-osx.sh

